name: test aws
on:
   workflow_dispatch:
jobs:
  deploy:
    name: Tests AWS credentials generation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Works as exptected ==============================================================

    - name: assume role with admin credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 1200
        role-skip-session-tagging: true

    - name: run kubectl as admin
      run: |
        aws eks update-kubeconfig --name eks-cluster-csi-sms-dev
        kubectl get namespaces
    # ================================================================================

    - name: assume role with CICD credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
        role-to-assume: ${{ secrets.CICD_AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 1200
        role-skip-session-tagging: true

    - name: run kubectl as CICD user
      run: |
        aws eks update-kubeconfig --name eks-cluster-csi-sms-dev
        kubectl get namespaces

